name: Say Hello
on:
  workflow_dispatch:
    inputs: 
      who-to-greet:
        description: "Who are we saying Hello to?"
        required: false
        default: "Eddie"
  
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        uses: driis/hello-world-docker-action@v1
      
